version: '3.7'

services:
  pselasticsearch:
    image: elasticsearch:7.8.1
    environment:
      - discovery.type=single-node
    ports:
    - "9200:9200"
    - "9300:9300"
    networks:
    - perfsonar
  lookup-service:
    image: perfsonar:lookup-service
    ports:
      - "8090:8090"
    depends_on:
      - "pselasticsearch"
    volumes:
      - .:/lookup-service
    networks:
      - perfsonar
    links:
      - "pselasticsearch:elasticsearch"
    command: ["/lookup-service/docker-utils/wait-for-it.sh", "-t", "60", "pselasticsearch:9200", "--", "java", "-jar", "/lookup-service/simple-lookup-service-server/target/simple-lookup-service-server-3.0-SNAPSHOT.one-jar.jar", "-c", "/lookup-service/simple-lookup-service-server/etc/", "-l", "/lookup-service/simple-lookup-service-server/etc/log4j2.properties"]
  logstash:
    image: logstash:7.8.0
    ports:
    - "5044:5044"
    - "9600:9600"
    networks:
    - perfsonar
    depends_on:
    - pselasticsearch
    environment:
    - monitoring.enabled=false
    volumes:
      - ./logstash_pipeline/:/usr/share/logstash/pipeline/
    links:
    - "pselasticsearch:elasticsearch"
  kibana:
    image: kibana:7.8.1
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    links:
    - "pselasticsearch:elasticsearch"
    networks:
      - perfsonar
  ps_host:
    image: perfsonar/testpoint:latest
    volumes:
    - ./perfsonar-client/lsregistrationdaemon.conf:/etc/perfsonar/lsregistrationdaemon.conf
    - ./perfsonar-client/lsregistrationdaemon-logger.conf:/etc/perfsonar/lsregistrationdaemon-logger.conf
    networks:
    - perfsonar
    links:
    - "lookup-service:sls"
networks:
  perfsonar:
    driver: bridge