version: '3.8'
services:
  alma8:
    image: ghcr.io/perfsonar/unibuild/alma8:latest
    volumes:
      -  .:/app
  centos7:
    image: ghcr.io/perfsonar/unibuild/centos7:latest
    network_mode: "host"
    volumes:
      - .:/app
  debian10:
    image: ghcr.io/perfsonar/unibuild/debian10:latest
    volumes:
      -  .:/app
